### PR TITLE
Make lib usable with C++

### LINKED ISSUE #63: Including header files in C++ sources makes builds fail
Due to name mangling in C++, including the header files makes it impossible for the linker to find the symbols.

One way to fix that is to wrap #includes of this library like so:
```C++
extern "C" {
    #include <stdio.h>
    #include <conio.h>
}
```
Another way is, to do this for the users of the library in it's headers using the #define __cplusplus to determine the build context.

Like so:
```C
/**
 * @file fileio.h
 * @brief File I/O functions
 *
 * If in C64 mode you must call `mega65_io_enable()` found in `memory.h`
 * before using any of the fileio functions.
 */

#ifndef __MEGA65_FILEIO_H
#define __MEGA65_FILEIO_H

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
// Being compiled by a C++ compiler, inhibit name mangling
extern "C" {
#endif

/*
... lots of defines
*/

#ifdef __cplusplus
} // End of extern "C"
#endif

#endif // __MEGA65_FILEIO_H
```

### PR DESCRIPTION
**Pull request by jwupf**
Add 'extern "C"' to function definitions to inhibit name mangling if used in C++ sources.
Closes #63.

## Checklist

Thanks a lot for your contribution!
Please tick off the following:

- Tests run successfully (i.e. `make test`)
  - [ ] using the CC65 compiler
  - [ ] using the LLVM/Clang compiler
- [ ] [Doxygen](https://www.doxygen.nl/index.html) style tags are used for public API
- [X] Source code is properly formatted; run e.g. `clang-format -i <file>`
- [X] I agree to the [License](https://github.com/MEGA65/mega65-libc/blob/master/LICENSE) of this repository

I did build with CC65. I can building with Clang and run the tests after setting up my environment for that(if I find the time). But I could use the lib with the changes in my application development environment. I have no such environment setup for this lib, yet.

I did not change comments, so I did not tick that item off.

### CODE REVIEW

**Review by mlund — APPROVED** [review]
Thanks, this looks good! A minor thing: there's unrelated code-formatting included in the commits. It seems harmless, but please double-check that it adheres to clang-format, or better change this in in a separate PR.

**Comment by jwupf** [comment]
That changes come from the commit hooks. I can remove them and add a PR for them.

**Comment by mlund** [comment]
> That changes come from the commit hooks. I can remove them and add a PR for them.

No need; they are pretty small so let's just merge.

**Comment by jwupf** [comment]
20 minutes playing with git later ... OK ;-)

**Pull request merged**
